I AM A CODER I AM A CODER I AM A CODER
yogstation13/yogbot-kt pull request #134
Opened 2023-11-20 02:33 UTC by Therandomhoboo

![i am a coder](https://github.com/yogstation13/yogbot-kt/assets/116853115/006fbcc9-3956-4f44-9691-992e987941e4)

We need this for all our coders out there, so we can tell Baimou we are indeed coders

2023-11-24 03:33 UTC, adamsong requested changes
Image kinda meh

2023-11-24 03:33 UTC, adamsong commented on src/main/java/net/yogstation/yogbot/listeners/commands/image/CoderCommand.kt
>  		"https://cdn.discordapp.com/attachments/892167119154872391/1161764164788830328/and_if_we_help.png" // Helping out
Forgot a comma

2023-11-24 15:56 UTC, Therandomhoboo commented on src/main/java/net/yogstation/yogbot/listeners/commands/image/CoderCommand.kt
>  		"https://cdn.discordapp.com/attachments/892167119154872391/1161764164788830328/and_if_we_help.png" // Helping out
Doneskis

2023-11-24 15:56 UTC, Therandomhoboo commented
> Image kinda meh

Thank you, I didn't want it to be too good otherwise people would ask me to do more.

2024-01-31 01:38 UTC, Therandomhoboo commented
> Image kinda meh

RIP

2024-02-19 01:27 UTC, merged