Fix relay channel displaying undecoded HTML entities
yogstation13/yogbot-kt pull request #98
Opened 2023-03-05 19:33 UTC by hedgehog1029

In the #ooc channel, a couple of characters show up as HTML entities:

Message sent as `#&;`:
![shown as #&amp;;](https://user-images.githubusercontent.com/3532945/222981175-dfeda9cd-92fa-480f-9965-3557dfd357d7.png)

Messages with apostrophes `'`:
![apostrophe rendered as &#39;](https://user-images.githubusercontent.com/3532945/222981250-a7925dbb-2a86-4f45-bb6e-aec7163096e3.png)

I've gone ahead and applied the decoding to all of the relay endpoints. Interestingly `UnclaimedTicketEndpoint` already did this?

2023-03-05 19:33 UTC, hedgehog1029 commented
did my editor change the newlines gdi

2023-03-21 06:01 UTC, adamsong requested changes
Fix newlines

2023-03-21 12:50 UTC, hedgehog1029 commented
Fixed up. worth noting those specific files are CRLF for some reason

2023-04-15 19:30 UTC, adamsong approved these changes

2023-04-15 19:33 UTC, merged